export const AFNPRO_EXERCISE_ADS_LIST_REQUEST = 'AFNPRO_EXERCISE_ADS_LIST_REQUEST';
export const AFNPRO_EXERCISE_ADS_LIST_SUCCESS = 'AFNPRO_EXERCISE_ADS_LIST_SUCCESS';
export const AFNPRO_EXERCISE_ADS_LIST_FAILURE = 'AFNPRO_EXERCISE_ADS_LIST_FAILURE';

export function AdsListRequestAction() {
  return { type: AFNPRO_EXERCISE_ADS_LIST_REQUEST };
}
